import { api } from './client'
export const getUsers = (params?: any) => api.get('/users', { params })
export const getUser = (id: number) => api.get(`/users/${id}`)
export const createUser = (data: any) => api.post('/users', data)
export const updateUser = (id: number, data: any) => api.patch(`/users/${id}`, data)
export const deactivateUser = (id: number) => api.patch(`/users/${id}/deactivate`)
export const activateUser = (id: number) => api.patch(`/users/${id}/activate`)
export const getUserActivity = (id: number) => api.get(`/users/${id}/activity`)
export const getRoles = (params?: any) => api.get('/users/roles', { params })
export const createRole = (data: any) => api.post('/users/roles', data)
export const updateRole = (id: number, data: any) => api.patch(`/users/roles/${id}`, data)
export const deactivateRole = (id: number) => api.patch(`/users/roles/${id}/deactivate`)
export const restoreRole = (id: number) => api.patch(`/users/roles/${id}/restore`)
export const purgeRole = (id: number) => api.delete(`/users/roles/${id}/purge`)
export const getPermissions = () => api.get('/users/permissions')
export const getRolePermissions = (id: number) => api.get(`/users/roles/${id}/permissions`)
export const setRolePermissions = (id: number, permissions: string[]) => api.put(`/users/roles/${id}/permissions`, { permissions })
export const getDashboard = () => api.get('/analytics/dashboard')
export const getProjectAnalytics = (id: number) => api.get(`/analytics/projects/${id}`)
export const getTeamAnalytics = () => api.get('/analytics/team')
